### ISSUE TITLE
Finishing a keg by drinking the last of it does not trigger a `KEG_ENDED` event

### ISSUE THREAD

**Issue by justanr** [Kegbot/kegbot-server#352]
[Offending line](https://github.com/Kegbot/kegbot-server/blob/4f510310ac2f823a956721893a605c758d99f4a1/pykeg/core/models.py#L1276)

This should be moved *after* the drink calculation. Then it can make a determination if it should fire a `KEG_VOLUME_LOW` or a `KEG_ENDED` event depending on if it is empty or not.

**Comment by mik3y** [comment]
Cleaning up some ancient issues. In case it is still of interest: Kegs ending, and the corresponding `KEG_ENDED` event, can only happen manually.

**Comment by justanr** [comment]
Why is that? All the information for sending the event is readily available in that call, just further down. Or would a separate KEG\_EMPTY event be more appropriate?

**Comment by mik3y** [comment]
Right now the semantics of `KEG_ENDED` indicate someone has manually marked the keg as finished (which in turn can trigger things in plugins, such as tweeting).

Another real-world consideration is that buggy controllers can sometimes over-report volume, which can be fixed by adjusting or canceling the drink. Automatically ending the keg would be an extra side-effect.

I'd be +1 to a patch adding a new event.
